build:
  image: node:5.2.0
  commands:
    - npm install
    - npm test
notify:
  email:
    from: nukrs.w@gmail.com
    host: smtp.mailgun.org
    port: 587
    username: nukr
    password: akgeto0g
    recipients:
      - nukrs.w@gmail.com