build:
  image: node:5.2.0
  commands:
    - npm install
    - npm test
notify:
  email:
    from: admin@nukr.tw
    host: smtp.mailgun.org
    port: 587
    username: postmaster@nukr.tw
    password: cca539e52d6f744e82936fce01bd9a1e
    recipients:
      - nukrs.w@gmail.com
deploy:
  rsync:
    user: nukrs_w
    host: 104.155.196.26
    delete: false
    recursive: true
    source: /drone/src/github.com/nukr/mtg-redux
    target: /home/nukrs_w/mtg-redux